:notitle:
:keywords: catroof, ratbagd, libratbag, piper, dbus, d-bus, zbus, c, rust, python3, gtk, gnome, qt, kde
:docinfo: private-head,private-header

= catroof

....
            _                    __ 
           | |                  / _|
   ___ __ _| |_ _ __ ___   ___ | |_ 
  / __/ _` | __| '__/ _ \ / _ \|  _|
 | (_| (_| | |_| | | (_) | (_) | |  
  \___\__,_|\__|_|  \___/ \___/|_|  
                                    
                                    
....

.WORK IN PROGRESS
[NOTE]
This is Work In Progress.

https://github.com/libratbag/libratbag[ratbagd]-like device manager for configuring settings of audio, midi and surface control devices.

This project aims to provide:

 * device manager D-Bus service that implements
   device enumeration, configuration and profile
   management.
 * User interface frontends, including but not limited to:
 ** GTK3 frotnend via GNOME introspection (gcatroof)
    See https://github.com/libratbag/piper[piper] for the libratbag equivalent.
 ** ncurses frontend (ncatroof)
 ** commandline control via catroof_control
 ** QT (KDE) frontend
 ** WebUI frontend via D-Bus to HTTP


++++
<div class="paragraph">Example output of lscatroof that shows various sysfs devices and their mapping to ALSA</div>
<div class="stdout">
<pre class="stdout">
card#0
  id: "hw:tegrahda"
  description: "tegrahda"
  Devices:
    Audio device#3
      id: "hw:tegrahda,3"
        1 capture subdevice(s)
card#1
  id: "hw:tegrasndt210ref"
  description: "tegrasndt210ref"
  Devices:
    Audio device#0
      id: "hw:tegrasndt210ref,0"
        1 duplex subdevice(s)
    Audio device#1
      id: "hw:tegrasndt210ref,1"
        1 duplex subdevice(s)
    Audio device#2
      id: "hw:tegrasndt210ref,2"
        1 duplex subdevice(s)
    Audio device#3
      id: "hw:tegrasndt210ref,3"
        1 duplex subdevice(s)
    Audio device#4
      id: "hw:tegrasndt210ref,4"
        1 duplex subdevice(s)
    Audio device#5
      id: "hw:tegrasndt210ref,5"
        1 duplex subdevice(s)
    Audio device#6
      id: "hw:tegrasndt210ref,6"
        1 duplex subdevice(s)
    Audio device#7
      id: "hw:tegrasndt210ref,7"
        1 duplex subdevice(s)
    Audio device#8
      id: "hw:tegrasndt210ref,8"
        1 duplex subdevice(s)
    Audio device#9
      id: "hw:tegrasndt210ref,9"
        1 duplex subdevice(s)
card#2
  id: "hw:U192k"
  description: "U192k"
  Devices:
    Audio device#0
      id: "hw:U192k,0"
        1 duplex subdevice(s)
    MIDI device#0
      id: "hw:U192k,0"
        1 duplex subdevice(s)
card#3
  id: "hw:U7"
  description: "U7"
  Devices:
    Audio device#0
      id: "hw:U7,0"
        1 duplex subdevice(s)
    Audio device#1
      id: "hw:U7,1"
        1 capture subdevice(s)
    Audio device#2
      id: "hw:U7,2"
        1 capture subdevice(s)
=========================================================================
 N SUBSYSTEM DEVPATH
-------------------------------------------------------------------------
 1  platform /70030000.hda
             [SOUND] ALSA CARD NO: 0
-------------------------------------------------------------------------
 2       usb /70090000.xusb/usb1/1-2/1-2.4/1-2.4.4/1-2.4.4.4
             [MNFCTR] FTDI
             [PRODCT] FT232R USB UART
             [SERIAL] AL029JTA
-------------------------------------------------------------------------
 3       usb /70090000.xusb/usb1/1-2/1-2.4/1-2.4.4/1-2.4.4.2
             [MNFCTR] Prolific Technology Inc.
             [PRODCT] USB-Serial Controller
-------------------------------------------------------------------------
 4       hid /70090000.xusb/usb1/1-2/1-2.4/1-2.4.4/1-2.4.4.1/1-2.4.4.1.1/1-2.4.4.1.1:1.1/0003:046D:C221.000E
             [INPUT]
-------------------------------------------------------------------------
 5       hid /70090000.xusb/usb1/1-2/1-2.4/1-2.4.4/1-2.4.4.1/1-2.4.4.1.1/1-2.4.4.1.1:1.0/0003:046D:C221.000D
             [INPUT]
-------------------------------------------------------------------------
 6       usb /70090000.xusb/usb1/1-2/1-2.4/1-2.4.4/1-2.4.4.1/1-2.4.4.1.1
             [MNFCTR] Logitech
             [PRODCT] Logitech Gaming Keyboard
-------------------------------------------------------------------------
 7       hid /70090000.xusb/usb1/1-2/1-2.4/1-2.4.4/1-2.4.4.1/1-2.4.4.1.4/1-2.4.4.1.4:1.0/0003:046D:C222.000F
             [INPUT]
-------------------------------------------------------------------------
 8       usb /70090000.xusb/usb1/1-2/1-2.4/1-2.4.4/1-2.4.4.1/1-2.4.4.1.4
             [MNFCTR] G15 Keyboard
             [PRODCT] G15 Keyboard
-------------------------------------------------------------------------
 9       hid /70090000.xusb/usb1/1-2/1-2.4/1-2.4.4/1-2.4.4.1/1-2.4.4.1.2/1-2.4.4.1.2:1.0/0003:045E:001E.0010
             [INPUT]
-------------------------------------------------------------------------
10       usb /70090000.xusb/usb1/1-2/1-2.4/1-2.4.4/1-2.4.4.1/1-2.4.4.1.2
             [MNFCTR] Microsoft
             [PRODCT] Microsoft IntelliMouse® Explorer
-------------------------------------------------------------------------
11       usb /70090000.xusb/usb1/1-2/1-2.4/1-2.4.4/1-2.4.4.1
             [MNFCTR] Logitech
             [PRODCT] Logitech G15 Keyboard
-------------------------------------------------------------------------
12       usb /70090000.xusb/usb1/1-2/1-2.4/1-2.4.4
             [MNFCTR] GenesysLogic
             [PRODCT] USB2.0 Hub
-------------------------------------------------------------------------
13       usb /70090000.xusb/usb1/1-2/1-2.4/1-2.4.2/1-2.4.2:1.0
             [SOUND] ALSA CARD NO: 3
-------------------------------------------------------------------------
14       hid /70090000.xusb/usb1/1-2/1-2.4/1-2.4.2/1-2.4.2:1.4/0003:1043:857C.0006
             [INPUT]
-------------------------------------------------------------------------
15       usb /70090000.xusb/usb1/1-2/1-2.4/1-2.4.2
             [MNFCTR] ASUS
             [PRODCT] Xonar U7
-------------------------------------------------------------------------
16       usb /70090000.xusb/usb1/1-2/1-2.4/1-2.4.3/1-2.4.3:1.0
             [SOUND] ALSA CARD NO: 2
-------------------------------------------------------------------------
17       usb /70090000.xusb/usb1/1-2/1-2.4/1-2.4.3
             [MNFCTR] BEHRINGER
             [PRODCT] UMC404HD 192k
-------------------------------------------------------------------------
18       usb /70090000.xusb/usb1/1-2/1-2.4
             [MNFCTR] GenesysLogic
             [PRODCT] USB2.0 Hub
-------------------------------------------------------------------------
19       usb /70090000.xusb/usb1/1-2
             [MNFCTR] Generic
             [PRODCT] 4-Port USB 2.1 Hub
-------------------------------------------------------------------------
20       usb /70090000.xusb/usb1
             [MNFCTR] Linux 4.9.299-5305-27261-geebda4d2b455 xhci-hcd
             [PRODCT] xHCI Host Controller
             [SERIAL] 70090000.xusb
-------------------------------------------------------------------------
21       usb /70090000.xusb/usb2/2-1/2-1.3
             [MNFCTR] TOSHIBA
             [PRODCT] External USB 3.0
             [SERIAL] 201503310007F
-------------------------------------------------------------------------
22       usb /70090000.xusb/usb2/2-1/2-1.1
             [MNFCTR] TOSHIBA
             [PRODCT] External USB 3.0
             [SERIAL] 201503310007F
-------------------------------------------------------------------------
23       usb /70090000.xusb/usb2/2-1/2-1.4
             [MNFCTR] GenesysLogic
             [PRODCT] USB3.0 Hub
-------------------------------------------------------------------------
24       usb /70090000.xusb/usb2/2-1
             [MNFCTR] Generic
             [PRODCT] 4-Port USB 3.1 Hub
-------------------------------------------------------------------------
25       usb /70090000.xusb/usb2
             [MNFCTR] Linux 4.9.299-5305-27261-geebda4d2b455 xhci-hcd
             [PRODCT] xHCI Host Controller
             [SERIAL] 70090000.xusb
-------------------------------------------------------------------------
26  platform /sound
             [SOUND] ALSA CARD NO: 1
</pre>
</div>
++++

Development happens in GIT:

 * https://gitea.ladish.org/LADI/catroof[catroof repo at LADI project Gitea]
 * https://github.com/LADI/catroof[catroof repo of LADI project at GitHub]

See also:

 * https://jackdbus.ladish.org/[jackdbus]
 * https://ladish.org/[LADISH Session Handler]

For related discussions, you are invited to join
https://libera.chat/[Libera.Chat] channel #ladi
