:notitle:
:keywords: catroof, ratbagd, libratbag, piper, dbus, d-bus, zbus, c, rust, python3, gtk, gnome, qt, kde
:docinfo: private-head,private-header

= catroof

....
            _                    __ 
           | |                  / _|
   ___ __ _| |_ _ __ ___   ___ | |_ 
  / __/ _` | __| '__/ _ \ / _ \|  _|
 | (_| (_| | |_| | | (_) | (_) | |  
  \___\__,_|\__|_|  \___/ \___/|_|  
                                    
                                    
....

.WORK IN PROGRESS
[NOTE]
This is Work In Progress.

https://github.com/libratbag/libratbag[ratbagd]-like device manager for configuring settings of audio, midi and surface control devices.

This project aims to provide:

 * device manager D-Bus service that implements
   device enumeration, configuration and profile
   management.
 * User interface frontends, including but not limited to:
 ** GTK3 frotnend via GNOME introspection (gcatroof)
    See https://github.com/libratbag/piper[piper] for the libratbag equivalent.
 ** ncurses frontend (ncatroof)
 ** commandline control via catroof_control
 ** QT (KDE) frontend
 ** WebUI frontend via D-Bus to HTTP


++++
<div class="paragraph">Example output of lscatroof that shows various sysfs devices and their mapping to ALSA</div>
<div class="stdout">
<pre class="stdout">
            _                    __ 
           | |                  / _|
   ___ __ _| |_ _ __ ___   ___ | |_ 
  / __/ _` | __| '__/ _ \ / _ \|  _|
 | (_| (_| | |_| | | (_) | (_) | |  
  \___\__,_|\__|_|  \___/ \___/|_|  
                                    
                                    
Version 0-dev ffa2656fb3b69cc32ae3fd61a7dffd88c78efac3
Built Fri Jul 14 20:37:43 2023
                                    
card#0
  id: "hw:tegrahda"
  description: "tegrahda"
  Devices:
    Audio device#3
      id: "hw:tegrahda,3"
        1 capture subdevice(s)
card#1
  id: "hw:tegrasndt210ref"
  description: "tegrasndt210ref"
  Devices:
    Audio device#0
      id: "hw:tegrasndt210ref,0"
        1 duplex subdevice(s)
    Audio device#1
      id: "hw:tegrasndt210ref,1"
        1 duplex subdevice(s)
    Audio device#2
      id: "hw:tegrasndt210ref,2"
        1 duplex subdevice(s)
    Audio device#3
      id: "hw:tegrasndt210ref,3"
        1 duplex subdevice(s)
    Audio device#4
      id: "hw:tegrasndt210ref,4"
        1 duplex subdevice(s)
    Audio device#5
      id: "hw:tegrasndt210ref,5"
        1 duplex subdevice(s)
    Audio device#6
      id: "hw:tegrasndt210ref,6"
        1 duplex subdevice(s)
    Audio device#7
      id: "hw:tegrasndt210ref,7"
        1 duplex subdevice(s)
    Audio device#8
      id: "hw:tegrasndt210ref,8"
        1 duplex subdevice(s)
    Audio device#9
      id: "hw:tegrasndt210ref,9"
        1 duplex subdevice(s)
card#2
  id: "hw:U7"
  description: "U7"
  Devices:
    Audio device#0
      id: "hw:U7,0"
        1 duplex subdevice(s)
    Audio device#1
      id: "hw:U7,1"
        1 capture subdevice(s)
    Audio device#2
      id: "hw:U7,2"
        1 capture subdevice(s)
card#3
  id: "hw:U192k"
  description: "U192k"
  Devices:
    Audio device#0
      id: "hw:U192k,0"
        1 duplex subdevice(s)
    MIDI device#0
      id: "hw:U192k,0"
        1 duplex subdevice(s)
=========================================================================
 N SUBSYSTEM DEVPATH
-------------------------------------------------------------------------
 1  platform /70030000.hda
             [SOUND] card0
-------------------------------------------------------------------------
 2       usb /70090000.xusb/usb1/1-2/1-2.4/1-2.4.4/1-2.4.4.4
             [MNFCTR] FTDI
             [PRODCT] FT232R USB UART
             [SERIAL] AL029JTA
-------------------------------------------------------------------------
 3       usb /70090000.xusb/usb1/1-2/1-2.4/1-2.4.4/1-2.4.4.2
             [MNFCTR] Prolific Technology Inc.
             [PRODCT] USB-Serial Controller
-------------------------------------------------------------------------
 4       usb /70090000.xusb/usb1/1-2/1-2.4/1-2.4.4/1-2.4.4.3
             [MNFCTR] Prolific Technology Inc.
             [PRODCT] USB-Serial Controller
-------------------------------------------------------------------------
 5       hid /70090000.xusb/usb1/1-2/1-2.4/1-2.4.4/1-2.4.4.1/1-2.4.4.1.1/1-2.4.4.1.1:1.1/0003:046D:C221.0003
             [INPUT] input3
             [EVENT] event3
-------------------------------------------------------------------------
 6       hid /70090000.xusb/usb1/1-2/1-2.4/1-2.4.4/1-2.4.4.1/1-2.4.4.1.1/1-2.4.4.1.1:1.0/0003:046D:C221.0002
             [INPUT] input2
             [EVENT] event2
-------------------------------------------------------------------------
 7       usb /70090000.xusb/usb1/1-2/1-2.4/1-2.4.4/1-2.4.4.1/1-2.4.4.1.1
             [MNFCTR] Logitech
             [PRODCT] Logitech Gaming Keyboard
-------------------------------------------------------------------------
 8       hid /70090000.xusb/usb1/1-2/1-2.4/1-2.4.4/1-2.4.4.1/1-2.4.4.1.4/1-2.4.4.1.4:1.0/0003:046D:C222.0005
             [INPUT] input5
             [EVENT] event5
-------------------------------------------------------------------------
 9       usb /70090000.xusb/usb1/1-2/1-2.4/1-2.4.4/1-2.4.4.1/1-2.4.4.1.4
             [MNFCTR] G15 Keyboard
             [PRODCT] G15 Keyboard
-------------------------------------------------------------------------
10       hid /70090000.xusb/usb1/1-2/1-2.4/1-2.4.4/1-2.4.4.1/1-2.4.4.1.2/1-2.4.4.1.2:1.0/0003:045E:001E.0004
             [INPUT] input4
             [EVENT] event4
-------------------------------------------------------------------------
11       usb /70090000.xusb/usb1/1-2/1-2.4/1-2.4.4/1-2.4.4.1/1-2.4.4.1.2
             [MNFCTR] Microsoft
             [PRODCT] Microsoft IntelliMouse® Explorer
-------------------------------------------------------------------------
12       usb /70090000.xusb/usb1/1-2/1-2.4/1-2.4.4/1-2.4.4.1
             [MNFCTR] Logitech
             [PRODCT] Logitech G15 Keyboard
-------------------------------------------------------------------------
13       usb /70090000.xusb/usb1/1-2/1-2.4/1-2.4.4
             [MNFCTR] GenesysLogic
             [PRODCT] USB2.0 Hub
-------------------------------------------------------------------------
14       usb /70090000.xusb/usb1/1-2/1-2.4/1-2.4.2/1-2.4.2:1.0
             [SOUND] card2
-------------------------------------------------------------------------
15       hid /70090000.xusb/usb1/1-2/1-2.4/1-2.4.2/1-2.4.2:1.4/0003:1043:857C.0001
             [INPUT] input1
             [EVENT] event1
-------------------------------------------------------------------------
16       usb /70090000.xusb/usb1/1-2/1-2.4/1-2.4.2
             [MNFCTR] ASUS
             [PRODCT] Xonar U7
-------------------------------------------------------------------------
17       usb /70090000.xusb/usb1/1-2/1-2.4/1-2.4.3/1-2.4.3:1.0
             [SOUND] card3
-------------------------------------------------------------------------
18       usb /70090000.xusb/usb1/1-2/1-2.4/1-2.4.3
             [MNFCTR] BEHRINGER
             [PRODCT] UMC404HD 192k
-------------------------------------------------------------------------
19       usb /70090000.xusb/usb1/1-2/1-2.4
             [MNFCTR] GenesysLogic
             [PRODCT] USB2.0 Hub
-------------------------------------------------------------------------
20       usb /70090000.xusb/usb1/1-2
             [MNFCTR] Generic
             [PRODCT] 4-Port USB 2.1 Hub
-------------------------------------------------------------------------
21       usb /70090000.xusb/usb1
             [MNFCTR] Linux 4.9.299-5305-27261-geebda4d2b455 xhci-hcd
             [PRODCT] xHCI Host Controller
             [SERIAL] 70090000.xusb
-------------------------------------------------------------------------
22      scsi /70090000.xusb/usb2/2-1/2-1.3/2-1.3:1.0/host2/target2:0:0/2:0:0:0
             [VENDOR] TO Exter
             [MODEL] nal USB 3.0     
             [WWID] naa.3020150331000760
             [BLOCK] sdc
-------------------------------------------------------------------------
23       usb /70090000.xusb/usb2/2-1/2-1.3
             [MNFCTR] TOSHIBA
             [PRODCT] External USB 3.0
             [SERIAL] 201503310007F
-------------------------------------------------------------------------
24      scsi /70090000.xusb/usb2/2-1/2-1.1/2-1.1:1.0/host0/target0:0:0/0:0:0:0
             [VENDOR] TO Exter
             [MODEL] nal USB 3.0     
             [WWID] naa.3020150331000760
             [BLOCK] sda
-------------------------------------------------------------------------
25       usb /70090000.xusb/usb2/2-1/2-1.1
             [MNFCTR] TOSHIBA
             [PRODCT] External USB 3.0
             [SERIAL] 201503310007F
-------------------------------------------------------------------------
26       usb /70090000.xusb/usb2/2-1/2-1.4
             [MNFCTR] GenesysLogic
             [PRODCT] USB3.0 Hub
-------------------------------------------------------------------------
27       usb /70090000.xusb/usb2/2-1
             [MNFCTR] Generic
             [PRODCT] 4-Port USB 3.1 Hub
-------------------------------------------------------------------------
28       usb /70090000.xusb/usb2
             [MNFCTR] Linux 4.9.299-5305-27261-geebda4d2b455 xhci-hcd
             [PRODCT] xHCI Host Controller
             [SERIAL] 70090000.xusb
-------------------------------------------------------------------------
29  platform /sound
             [SOUND] card1
</pre>
</div>
++++

Development happens in GIT:

 * https://gitea.ladish.org/LADI/catroof[catroof repo at LADI project Gitea]
 * https://github.com/LADI/catroof[catroof repo of LADI project at GitHub]

See also:

 * https://jackdbus.ladish.org/[jackdbus]
 * https://ladish.org/[LADISH Session Handler]

For related discussions, you are invited to join
https://libera.chat/[Libera.Chat] channel #ladi
